src/main/java/zti/ksiegarnia/model/ImageArea.java
package zti.ksiegarnia.model;

import java.io.Serializable;

public final class ImageArea implements Serializable {

    private static final long serialVersionUID = -2382340811618738146L;
    private String alt = null;
    private String coords = null;
    private String shape = null;

    public ImageArea() {
    }

    public ImageArea(String alt, String coords, String shape) {
        setAlt(alt);
        setCoords(coords);
        setShape(shape);
    }

    public String getAlt() {
        return (this.alt);
    }

    public void setAlt(String alt) {
        this.alt = alt;
    }

    public String getCoords() {
        return (this.coords);
    }

    public void setCoords(String coords) {
        this.coords = coords;
    }

    public String getShape() {
        return (this.shape);
    }

    public void setShape(String shape) {
        this.shape = shape;
    }
}

src/main/java/zti/ksiegarnia/ejb/BookRequestBean.java
package zti.ksiegarnia.ejb;

import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import zti.ksiegarnia.entity.Book;
import zti.ksiegarnia.exception.BookNotFoundException;
import zti.ksiegarnia.exception.BooksNotFoundException;
import zti.ksiegarnia.exception.OrderException;
import zti.ksiegarnia.web.managedbeans.ShoppingCart;
import zti.ksiegarnia.web.managedbeans.ShoppingCartItem;
import javax.ejb.EJBException;
import javax.ejb.Stateful;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Stateful
public class BookRequestBean {

    @PersistenceContext
    private EntityManager em;
    private static final Logger logger =
            Logger.getLogger("ksiegarnia.ejb.BookRequestBean");

    public BookRequestBean() throws Exception {
    }

    public void setEntityManager(EntityManager em) {
        this.em = em;
    }
    public void createBook(String bookId, String surname, String firstname,
            String title, Double price, Boolean onsale, Integer calendarYear,
            String description, Integer inventory) {
        try {
            Book book = new Book(bookId, surname, firstname, title, price,
                    onsale, calendarYear, description, inventory);
            logger.log(Level.INFO, "Created book {0}", bookId);
            em.persist(book);
            logger.log(Level.INFO, "Persisted book {0}", bookId);
        } catch (Exception ex) {
            throw new EJBException(ex.getMessage());
        }
    }

    public List<Book> getBooks() throws BooksNotFoundException {
        try {
            return (List<Book>) em.createNamedQuery("findBooks").getResultList();
        } catch (Exception ex) {
            throw new BooksNotFoundException(
                    "Could not get books: " + ex.getMessage());
        }
    }

    public Book getBook(String bookId) throws BookNotFoundException {
        Book requestedBook = em.find(Book.class, bookId);

        if (requestedBook == null) {
            throw new BookNotFoundException("Couldn't find book: " + bookId);
        }

        return requestedBook;
    }

    public void buyBooks(ShoppingCart cart) throws OrderException {
        Collection<ShoppingCartItem> items = cart.getItems();
        Iterator<ShoppingCartItem> i = items.iterator();

        try {
            while (i.hasNext()) {
                ShoppingCartItem sci = (ShoppingCartItem) i.next();
                Book bd = (Book) sci.getItem();
                String id = bd.getBookId();
                int quantity = sci.getQuantity();
                buyBook(id, quantity);
            }
        } catch (OrderException ex) {
            throw new OrderException("Commit failed: " + ex.getMessage());
        }
    }

    public void buyBook(String bookId, int quantity)
            throws OrderException {
        try {
            Book requestedBook = em.find(Book.class, bookId);

            if (requestedBook != null) {
                int inventory = requestedBook.getInventory();

                if ((inventory - quantity) >= 0) {
                    int newInventory = inventory - quantity;
                    requestedBook.setInventory(newInventory);
                } else {
                    throw new OrderException(
                            "Not enough of " + bookId
                            + " in stock to complete order.");
                }
            }
        } catch (OrderException ex) {
            throw new OrderException(
                    "Couldn't purchase book: " + bookId + ex.getMessage());
        }
    }

    public void updateInventory(ShoppingCart cart) throws OrderException {
        try {
            buyBooks(cart);
        } catch (OrderException ex) {
            throw new OrderException("Inventory update failed: " + ex.getMessage());
        }
    }
}

src/main/java/zti/ksiegarnia/ejb/ConfigBean.java
package zti.ksiegarnia.ejb;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.ejb.Singleton;
import javax.ejb.Startup;

@Singleton
@Startup
public class ConfigBean {

    @EJB
    private BookRequestBean request;

    @PostConstruct
    public void createData() {
        request.createBook("201", "Walls", "",
                "Spring w Akcji. Wydanie III",
                30.75, false, 2005, "Super książka.", 20);
        request.createBook("202", "Martin", "",
                "Czysty kod. Podręcznik dobrego programisty", 40.75, true,
                2010, "Super książka.", 20);
        request.createBook("203", "Robert", "Love",
                "Jądro Linuksa. Przewodnik programisty",
                27.75, false, 2010, "Super książka.", 20);
        request.createBook("205", "Loeliger", "Matthew McCullough",
                "Kontrola wersji z systemem Git. Narzędzia i techniki programistów. Wydanie II",
                10.75, true, 2008, "Super książka.", 20);
        request.createBook("206", "Hunt", "Dave Thomas",
                "JUnit. Pragmatyczne testy jednostkowe w Javie",
                30.00, true, 2008, "Super książka.", 20);
        request.createBook("207", "Howard", "Goldberg",
                "XML. Szybki start. Wydanie II", 30.95, true,
                2010, "Super książka.", 20);

    }
}

src/main/java/zti/ksiegarnia/web/managedbeans/AbstractBean.java
package zti.ksiegarnia.web.managedbeans;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.ResourceBundle;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@SessionScoped
public class AbstractBean implements Serializable {

    private static final long serialVersionUID = -3375564172975657665L;
    @Inject
    ShoppingCart cart;

    protected FacesContext context() {
        return (FacesContext.getCurrentInstance());
    }

    protected void message(String clientId, String key) {
        String text;

        try {
            ResourceBundle bundle = ResourceBundle.getBundle(
                    "zti.ksiegarnia.web.messages.Messages",
                    context().getViewRoot().getLocale());
            text = bundle.getString(key);
        } catch (Exception e) {
            text = "???" + key + "???";
        }

        context().addMessage(clientId, new FacesMessage(text));
    }

    protected void message(String clientId, String key, Object[] params) {
        String text;

        try {
            ResourceBundle bundle = ResourceBundle.getBundle(
                    "zti.ksiegarnia.web.messages.Messages",
                    context().getViewRoot().getLocale());
            text = bundle.getString(key);
        } catch (Exception e) {
            text = "???" + key + "???";
        }

        if ((params != null) && (params.length > 0)) {
            text = MessageFormat.format(text, params);
        }

        context().addMessage(clientId, new FacesMessage(text));
    }
}

src/main/java/zti/ksiegarnia/web/managedbeans/BookDetailsBean.java
package zti.ksiegarnia.web.managedbeans;

import java.io.Serializable;
import zti.ksiegarnia.entity.Book;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named("details")
@SessionScoped
public class BookDetailsBean extends AbstractBean implements Serializable {

    private static final long serialVersionUID = 2209748452115843974L;

    public String add() {
        Book book = (Book) context().getExternalContext()
                .getSessionMap().get("selected");
        cart.add(book.getBookId(), book);
        message(null, "ConfirmAdd", new Object[]{book.getTitle()});

        return ("bookcatalog");
    }
}

src/main/java/zti/ksiegarnia/web/managedbeans/BookstoreBean.java
package zti.ksiegarnia.web.managedbeans;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import zti.ksiegarnia.ejb.BookRequestBean;
import zti.ksiegarnia.entity.Book;
import zti.ksiegarnia.exception.BookNotFoundException;
import zti.ksiegarnia.exception.BooksNotFoundException;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.FacesException;
import javax.inject.Named;

@Named("store")
@SessionScoped
public class BookstoreBean extends AbstractBean implements Serializable {

    private static final Logger logger =
            Logger.getLogger("ksiegarnia.web.managedBeans.BookStoreBean");
    private static final long serialVersionUID = 7829793160074383708L;
    private Book featured = null;
    protected String title;
    @EJB
    BookRequestBean bookRequestBean;

    public Book getFeatured() {
        int featuredBookPos = 4;
        if (featured == null) {
            try {
                featured = (Book) bookRequestBean.getBooks().get(featuredBookPos);
            } catch (BooksNotFoundException e) {
                throw new FacesException("Could not get books: " + e);
            }
        }

        return (featured);
    }

    public String add() {
        Book book = getFeatured();
        cart.add(book.getBookId(), book);
        message(null, "ConfirmAdd", new Object[]{book.getTitle()});

        return ("bookcatalog");
    }

    public String addSelected() {
        logger.log(Level.INFO, "Entering BookstoreBean.addSelected");
        try {
            String bookId = (String) context().getExternalContext().
                    getSessionMap().get("bookId");
            Book book = bookRequestBean.getBook(bookId);
            cart.add(bookId, book);
            message(null, "ConfirmAdd", new Object[]{book.getTitle()});
        } catch (BookNotFoundException e) {
            throw new FacesException("Could not get book: " + e);
        }
        return ("bookcatalog");
    }

    public String details() {
        context().getExternalContext().getSessionMap().put(
                "selected",
                getFeatured());

        return ("bookdetails");
    }

    public String selectedDetails() {
        logger.log(Level.INFO, "Entering BookstoreBean.selectedDetails");
        try {
            String bookId = (String) context().getExternalContext().getSessionMap().get("bookId");
            Book book = bookRequestBean.getBook(bookId);
            context().getExternalContext().getSessionMap().put("selected", book);
        } catch (BookNotFoundException e) {
            throw new FacesException("Could not get book: " + e);
        }
        return ("bookdetails");
    }

    public String getSelectedTitle() {
        logger.log(Level.INFO, "Entering BookstoreBean.getSelectedTitle");
        try {
            String bookId = (String) context().getExternalContext().getSessionMap().get("bookId");
            Book book = bookRequestBean.getBook(bookId);
            title = book.getTitle();
        } catch (BookNotFoundException e) {
            throw new FacesException("Could not get book title: " + e);
        }
        return title;
    }

    public List<Book> getBooks() {
        try {
            return bookRequestBean.getBooks();
        } catch (BooksNotFoundException e) {
            throw new FacesException("Exception: " + e);
        }
    }
}

src/main/java/zti/ksiegarnia/web/managedbeans/CashierBean.java
package zti.ksiegarnia.web.managedbeans;

import java.util.Calendar;
import java.util.Date;
import zti.ksiegarnia.ejb.BookRequestBean;
import zti.ksiegarnia.exception.OrderException;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.component.UIOutput;
import javax.faces.component.UISelectBoolean;
import javax.faces.model.SelectItem;
import javax.inject.Named;

@Named
@RequestScoped
public class CashierBean extends AbstractBean {

    private static final long serialVersionUID = -9221440716172304017L;
    @EJB
    BookRequestBean bookRequestBean;
    private String name = null;
    private String creditCardNumber = null;
    private Date shipDate;
    private String shippingOption = "2";
    UIOutput specialOfferText = null;
    UISelectBoolean specialOffer = null;
    UIOutput thankYou = null;
    private String stringProperty = "This is a String property";
    private String[] newsletters;
    private static final SelectItem[] newsletterItems = {
        new SelectItem("Komputer Świat"),
        new SelectItem("PC Format"),
        new SelectItem("Jak Franek został kolejarzem"),
        new SelectItem("Co za życie")
    };

    public CashierBean() {
        this.newsletters = new String[0];
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public String getCreditCardNumber() {
        return creditCardNumber;
    }

    public void setCreditCardNumber(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }

    public void setNewsletters(String[] newsletters) {
        this.newsletters = newsletters;
    }

    public String[] getNewsletters() {
        return this.newsletters;
    }

    public SelectItem[] getNewsletterItems() {
        return newsletterItems;
    }

    public Date getShipDate() {
        return this.shipDate;
    }

    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    public void setShippingOption(String shippingOption) {
        this.shippingOption = shippingOption;
    }

    public String getShippingOption() {
        return this.shippingOption;
    }

    public UIOutput getSpecialOfferText() {
        return this.specialOfferText;
    }

    public void setSpecialOfferText(UIOutput specialOfferText) {
        this.specialOfferText = specialOfferText;
    }

    public UISelectBoolean getSpecialOffer() {
        return this.specialOffer;
    }

    public void setSpecialOffer(UISelectBoolean specialOffer) {
        this.specialOffer = specialOffer;
    }

    public UIOutput getThankYou() {
        return this.thankYou;
    }

    public void setThankYou(UIOutput thankYou) {
        this.thankYou = thankYou;
    }

    public String getStringProperty() {
        return (this.stringProperty);
    }

    public void setStringProperty(String stringProperty) {
        this.stringProperty = stringProperty;
    }

    public String submit() {
        int days = Integer.valueOf(shippingOption).intValue();
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DAY_OF_MONTH, days);
        setShipDate(cal.getTime());

        if ((cart.getTotal() > 100.00) && !specialOffer.isRendered()) {
            specialOfferText.setRendered(true);
            specialOffer.setRendered(true);

            return null;
        } else if (specialOffer.isRendered() && !thankYou.isRendered()) {
            thankYou.setRendered(true);

            return null;
        } else {
            try {
                bookRequestBean.updateInventory(cart);
            } catch (OrderException ex) {
                return "bookordererror";
            }

            cart.clear();

            return ("bookreceipt");
        }
    }
}

src/main/java/zti/ksiegarnia/web/managedbeans/CatalogBean.java
package zti.ksiegarnia.web.managedbeans;

import java.io.Serializable;
import java.util.List;
import zti.ksiegarnia.entity.Book;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named("catalog")
@SessionScoped
public class CatalogBean extends AbstractBean implements Serializable {

    private static final long serialVersionUID = -3594317405246398714L;
    private int totalBooks = 0;

    protected Book book() {
        Book book;
        book = (Book) context().getExternalContext()
           .getRequestMap().get("book");

        return (book);
    }

    public String add() {
        Book book = book();
        cart.add(book.getBookId(), book);
        message(null, "ConfirmAdd", new Object[]{book.getTitle()});

        return ("bookcatalog");
    }

    public String details() {
        context().getExternalContext().getSessionMap().put("selected", book());

        return ("bookdetails");
    }

    public int getTotalBooks() {
        totalBooks = cart.getNumberOfItems();

        return totalBooks;
    }

    public void setTotalBooks(int totalBooks) {
        this.totalBooks = totalBooks;
    }

    public int getBookQuantity() {
        int bookQuantity = 0;
        Book book = book();

        if (book == null) {
            return bookQuantity;
        }

        List<ShoppingCartItem> results = cart.getItems();
        for (ShoppingCartItem item : results) {
            Book bd = (Book) item.getItem();

            if ((bd.getBookId()).equals(book.getBookId())) {
                bookQuantity = item.getQuantity();

                break;
            }
        }

        return bookQuantity;
    }
}

src/main/webapp/bookcashier.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!--

    Copyright (c) 2013 Oracle and/or its affiliates. All rights reserved.

    You may not modify, use, reproduce, or distribute this software except in
    compliance with  the terms of the License at:
    http://java.net/projects/javaeetutorial/pages/BerkeleyLicense

-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
                template="/bookstoreTemplate.xhtml"> 

    <ui:define name="top"></ui:define> 
    <ui:define name="content">
        <h:form id="bookcashier" >
            <p>
                <h:outputText value="#{bundle.Amount}" />
                <strong>
                    <h:outputText value="#{cart.total}">
                        <f:convertNumber currencySymbol="$" type="currency"/>
                    </h:outputText>
                </strong>
            </p>
            <p>
                <h:outputText value="#{bundle.Purchase}"/>
            </p>

            <h:panelGrid columns="2"
                         headerClass="list-header"
                         styleClass="list-background"
                         rowClasses="list-row-even, list-row-odd"
                         summary="#{bundle.CustomerInfo}"
                         title="#{bundle.Checkout}"
                         role="presentation">
                <!-- Panel header -->
                <f:facet name="header">
                    <h:outputText value="#{bundle.Checkout}"/>
                </f:facet>

                <!-- Customer name -->
                <h:outputLabel for="name" value="#{bundle.Name}" />
                <h:inputText id="name"
                             size="30"
                             value="#{cashierBean.name}"
                             required="true"
                             requiredMessage="#{bundle.ReqCustomerName}" >
                    <f:valueChangeListener
                        type="zti.ksiegarnia.listeners.NameChanged" /> 
                </h:inputText>
                <h:message styleClass="error-message" for="name"/>

                <!-- Credit card number -->
                <h:outputLabel for="ccno" value="#{bundle.CCNumber}"/>
                <h:inputText id="ccno" 
                             size="19"
                             value="#{cashierBean.creditCardNumber}"
                             required="true"
                             requiredMessage="#{bundle.ReqCreditCard}" >
                    <f:converter converterId="ccno"/>
                    <f:validateRegex 
                        pattern="\d{16}|\d{4} \d{4} \d{4} \d{4}|\d{4}-\d{4}-\d{4}-\d{4}"/> 
                </h:inputText>
                <h:message styleClass="error-message" for="ccno"/>

                <!-- Shipping option -->
                <h:outputLabel for="shippingOption" value="#{bundle.Shipping}"/>
                <h:selectOneMenu id="shippingOption"
                                 required="true"
                                 value="#{cashierBean.shippingOption}">
                    <f:selectItem itemValue="2"
                                  itemLabel="#{bundle.QuickShip}"/>
                    <f:selectItem itemValue="5"
                                  itemLabel="#{bundle.NormalShip}"/>
                    <f:selectItem itemValue="7"
                                  itemLabel="#{bundle.SaverShip}"/>
                </h:selectOneMenu>
                <h:message styleClass="error-message" for="shippingOption"/>

                <!-- Newsletter subscriptions -->
                <h:outputLabel for="newslettercheckbox" 
                               value="#{bundle.Newsletters}"/>
                <h:selectManyCheckbox id="newslettercheckbox"
                                      layout="pageDirection"
                                      value="#{cashierBean.newsletters}">
                    <f:selectItems value="#{cashierBean.newsletterItems}"/>
                </h:selectManyCheckbox>
                <h:message styleClass="error-message" for="newslettercheckbox"/>

                <h:message styleClass="error-message" for="fanClub" />

            </h:panelGrid>
            <h:panelGrid columns="2" 
                         columnClasses="special-offer, list-column-left" 
                         summary="#{bundle.DukeFanClub}" >
                <h:selectBooleanCheckbox id="fanClub" 
                                         rendered="false"
                                         binding="#{cashierBean.specialOffer}" />
                <h:outputLabel for="fanClub"
                               rendered="false"
                               binding="#{cashierBean.specialOfferText}"
                               value="#{bundle.DukeFanClub}" />
            </h:panelGrid>
            <h:panelGrid columns="1" 
                         columnClasses="special-offer" 
                         summary="#{bundle.ThanksMsg}">
                <h:outputText id="thanksMsg" 
                              rendered="false"
                              binding="#{cashierBean.thankYou}"
                              value="#{bundle.ThanksMsg}" />
                <h:commandButton value="#{bundle.Submit}"
                                 action="#{cashierBean.submit}">
                    <f:setPropertyActionListener 
                        target="#{cashierBean.stringProperty}" value=""/>
                </h:commandButton>
            </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/bookcatalog.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/bookstoreTemplate.xhtml">

    <ui:define name="top"></ui:define> 
    <ui:define name="content">
        <h:form>
            <p>
                <h:commandLink id="check"
                               action="bookshowcart"
                               immediate="true"
                               rendered="#{cart.numberOfItems > 0}">
                    <h:outputText value="#{bundle.CartCheck}"/>
                </h:commandLink>
                &nbsp;&nbsp;
                <h:outputText escape="false"
                              value="&nbsp;"
                              rendered="#{cart.numberOfItems > 0}"/>

                <h:commandLink id="clear"
                               action="#{cart.clear}"
                               immediate="true"
                               rendered="#{cart.numberOfItems > 0}">
                    <h:outputText value="#{bundle.ClearCart}"/>
                </h:commandLink>
                &nbsp;&nbsp;
                <h:outputText escape="false"
                              value="&nbsp;"
                              rendered="#{cart.numberOfItems > 0}"/>

                <h:commandLink id="buy"
                               action="#{cart.buy}"
                               immediate="true"
                               rendered="#{cart.numberOfItems > 0}">
                    <h:outputText value="#{bundle.Buy}"/>
                </h:commandLink>
                &nbsp;&nbsp;
                <h:outputText escape="false"
                              rendered="#{cart.numberOfItems > 0}"
                              value=""/>
            </p>
            <h:dataTable id="books"
                         value="#{store.books}"
                         var="book"
                         headerClass="list-header"
                         styleClass="list-background"
                         rowClasses="list-row-even, list-row-odd"
                         border="1" 
                         summary="#{bundle.BookCatalog}" >
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="#{bundle.Quantities}" />
                    </f:facet>
                    <h:outputText value="${catalog.bookQuantity}" />
                    <f:facet name="footer">
                        <h:outputText value="#{bundle.Total} #{catalog.totalBooks}" />
                    </f:facet>
                </h:column>

                <h:column>
                    <f:facet name="header">
                        <h:outputText value="#{bundle.ItemTitle}"/>
                    </f:facet>
                    <h:commandLink action="#{catalog.details}"
                                   value="#{book.title}">
                        <f:setPropertyActionListener target="#{requestScope.book}" 
                                                     value="#{book}"/>
                    </h:commandLink>
                </h:column>

                <h:column>
                    <f:facet name="header">
                        <h:outputText value="#{bundle.By}"/>
                    </f:facet>
                    <h:outputText value="#{book.firstname} #{book.surname}"/>
                </h:column>

                <h:column>
                    <f:facet name="header">
                        <h:outputText value="#{bundle.ItemPrice}"/>
                    </f:facet>
                    <h:outputText value="#{book.price}" >
                        <f:convertNumber currencySymbol="$" type="currency"/>
                    </h:outputText>
                </h:column>

                <h:column>
                    <f:facet name="header">
                        <h:outputText value="#{bundle.Inventory}" />
                    </f:facet>
                    <h:outputText value="#{book.inventory}"/>
                </h:column>

                <h:column>
                    <f:facet name="header">
                        <h:outputText  value="#{bundle.CartAdd}"/>
                    </f:facet>
                    <h:commandButton id="add"
                                     action="#{catalog.add}" 
                                     value="#{bundle.CartAdd}">
                        <f:setPropertyActionListener target="#{requestScope.book}" 
                                                     value="#{book}"/>
                    </h:commandButton>
                </h:column>

            </h:dataTable>
        </h:form>
        <div class="messagecolor">
            <h:messages showSummary="true" 
                        showDetail="false"
                        errorStyle="color: #d20005" 
                        infoStyle="color: blue"/>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/bookstore.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./bookstoreTemplate.xhtml">

    <ui:define name="top"></ui:define> 
    <ui:define name="content">
        <h:form>
            <p><b><h:outputText value="#{bundle.What}"/></b></p>
            <blockquote><p>
                    <em>
                        <h:commandLink id="details" 
                                       action="#{store.details}" 
                                       immediate="true">
                            <h:outputText value="#{store.featured.title}"/>
                        </h:commandLink>
                    </em>
                    <h:outputText value="#{bundle.Talk}"/>
                </p></blockquote>
            <p><b><h:outputText value="Wybrałeś:"/></b></p>
            <blockquote><p>
                    <em>
                        <h:commandLink id="selecteddetails" 
                                       action="#{store.selectedDetails}" 
                                       immediate="true">
                            <h:outputText value="#{store.selectedTitle}"/>
                        </h:commandLink>
                    </em>
                </p>
            </blockquote>
            <p>
                <h:commandLink id="addfeatured" 
                               action="#{store.add}" 
                               immediate="true">
                    <h:outputText value="#{bundle.CartAddFeatured}"/>
                </h:commandLink>
                &nbsp; &nbsp;
                <h:commandLink id="addselected" 
                               action="#{store.addSelected}" 
                               immediate="true">
                    <h:outputText value="#{bundle.CartAddSelected}"/>
                </h:commandLink>
                &nbsp; &nbsp;
                <h:commandLink id="catalog" action="bookcatalog">
                    <h:outputText value="#{bundle.Start}"/>
                </h:commandLink>
            </p>
        </h:form>
    </ui:define>
</ui:composition>